language: node_js

node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --global user.name 'JounQin'
  - git config --global user.email 'admin@1stg.me'

before_script:
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}

script:
  - set -e
  - yarn lint
  - yarn build --public-url /$TRAVIS_REPO_NAME/

deploy:
  provider: pages
  email: admin@1stg.me
  name: JounQin
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  allow_empty_commit: false
  local_dir: dist
  on:
    branch: master
